FROM docker.elastic.co/logstash/logstash:8.17.2

LABEL maintainer="Ilija Vukotic <ivukotic@cern.ch>"

USER root
RUN apt-get update && apt-get install -y nmap

# add postgresql driver
RUN mkdir -p /usr/share/logstash/java/
# RUN curl https://jdbc.postgresql.org/download/postgresql-42.3.1.jar -o /usr/share/logstash/java/postgresql-42.3.1.jar

RUN /usr/share/logstash/bin/logstash-plugin install logstash-filter-memcached

RUN mkdir /usr/share/logstash/configs
RUN mkdir /var/log/logstash && chown -R logstash /var/log/logstash

COPY logstash.yml /usr/share/logstash/config/logstash.yml

# COPY configs/ps-collector.conf /usr/share/logstash/configs/ps-collector.conf
COPY configs/ps-status.conf /usr/share/logstash/configs/ps-status.conf
COPY configs/ps-extra.conf /usr/share/logstash/configs/ps-extra.conf
COPY configs/ps-rtt.conf /usr/share/logstash/configs/ps-rtt.conf
COPY configs/ps-meta.conf /usr/share/logstash/configs/ps-meta.conf
COPY configs/ps-latencybg.conf /usr/share/logstash/configs/ps-latencybg.conf
COPY configs/ps-throughput.conf /usr/share/logstash/configs/ps-throughput.conf
COPY configs/ps-trace.conf /usr/share/logstash/configs/ps-trace.conf
COPY configs/ps-intake.conf /usr/share/logstash/configs/ps-intake.conf
COPY configs/es-output.conf /usr/share/logstash/configs/es-output.conf
COPY configs/nebraska.conf /usr/share/logstash/configs/nebraska.conf
COPY configs/ps-debug.conf /usr/share/logstash/configs/ps-debug.conf

COPY pipelines/ps-collector.yml /usr/share/logstash/config/pipelines.yml

COPY filters/* /usr/share/logstash/filters/

USER logstash