input { 
  http {
    host => "0.0.0.0"
    port => "8080"
  }
}

output { 
  if [test][type]=="trace" or [test][type]=="latencybg" or [test][type]=="throughput" or [test][type]=="rtt" {
    file{
      path => "/var/log/logstash/correct_%{[test][type]}.json"
    }
  } else {
    file{
      path => "/var/log/logstash/else.json"
    }
  }
  # stdout {
  #   codec => json
  # }
}