input { 
  http {
    host => "0.0.0.0"
    port => "8080"
  }
}

filter { 
  if [test][type]=="trace" or [test][type]=="latencybg" or [test][type]=="throughput" or [test][type]=="rtt" {

    mutate {
      remove_field => ["reference", "headers", "task", "schedule", "participants", "run", "tool", "@version", "schedule", "host"]
      copy => { "[run][end-time]" => "timestamp" }
      copy => { "@timestamp" => "ingest_timestamp" }
      copy => { "[test][spec][source]" => "src_host" }
      copy => { "[test][spec][dest]" => "dest_host" }
      copy => { "[tool][name]" => "tool_name" }
      rename => { "id" => "[@metadata][id]" } 
    }

    if [pull] {
      mutate{
        add_field => { "push" => false } 
      } 
    }
    else{
      mutate{
        add_field => { "push" => true } 
      }
    }

    memcached {
      id => "mem-thr-get"
      hosts => ["memcached"]
      get => {
        "ip_%{src_host}" => "[source]"
        "ip_%{dest_host}" => "[destination]"
        "vo_%{[src_host]}" => "[src_VO]"
        "vo_%{[dest_host]}" => "[dest_VO]"
        "sitename_%{[src_host]}" => "[src_site]"
        "sitename_%{[dest_host]}" => "[dest_site]"
        "rcsite_%{[src_host]}" => "[src_rcsite]"
        "rcsite_%{[dest_host]}" => "[dest_rcsite]"
        "netsite_%{[src_host]}" => "[src_netsite]"
        "netsite_%{[dest_host]}" => "[dest_netsite]"
        "production_%{[src_host]}" => "[src_production]"
        "production_%{[dest_host]}" => "[dest_production]"
      }
    }
    
    if ![source]{
      ruby { path => "/usr/share/logstash/filters/enrich_src.rb" }
      memcached {
        id => "mem-src-set"
        hosts => ["memcached"]
        ttl => 43200
        set => {
          "source" => "ip_%{src_host}"
        }
      }
    }    

    if ![destination]{
      ruby { path => "/usr/share/logstash/filters/enrich_dest.rb" }
      memcached {
        id => "mem-dest-set"
        hosts => ["memcached"]
        ttl => 43200
        set => {
          "destination" => "ip_%{dest_host}"
        }
      }
    }

    mutate { 
      convert => { "src_production" => "boolean" }
      convert => { "dest_production" => "boolean" }
      remove_field => ["pull"] 
      convert => { "push" => "boolean" }
      uppercase => [ "src_VO", "dest_VO" ]
    }

  } 
  else if ([type]=="status" or [type]=="meta") {
    memcached {
      id => "mem-meta-get"
      hosts => ["memcached"]
      get => {
        "vo_%{[ps_host]}" => "[VO]"
        "sitename_%{[ps_host]}" => "[site]"
        "rcsite_%{[ps_host]}" => "[rcsite]"
        "netsite_%{[ps_host]}" => "[netsite]"
        "production_%{[ps_host]}" => "[production]"
      }
    }
  }
}

output { 
  if [test][type]=="trace"{
    pipeline { send_to => ["ps-trace"] } 
  }
  else if [test][type]=="latencybg"{
    pipeline { send_to => ["ps-latencybg"] } 
  }
  else if [test][type]=="throughput"{
    pipeline { send_to => ["ps-throughput"] } 
  }
  else if [test][type]=="rtt"{
    pipeline { send_to => ["ps-rtt"] } 
  }
  else if [type]=="status" {
    pipeline { send_to => ["ps-status"] } 
  }
  else if [type]=="meta" {
    pipeline { send_to => ["ps-meta"] } 
  } 
  else {
    pipeline { send_to => ["ps-extra"] }
  }
}