input { pipeline { address => "ps-rtt" } }

filter {
  
  if ![result][succeeded] {
    drop{ }
  }

  if [source][ipv6] and [destination][ipv6] {
    mutate { 
      add_field => { "ipv6" => true } 
      add_field => { "src" => "%{[source][ipv6]}" } 
      add_field => { "dest" => "%{[destination][ipv6]}" } 
    }
  } else {
    mutate { 
      add_field => { "ipv6" => false } 
      add_field => { "src" => "%{[source][ipv4]}" } 
      add_field => { "dest" => "%{[destination][ipv4]}" } 
      }
  }

  mutate {
    add_field => { "[@metadata][type]" => "ps_rtt_write" } 
    remove_field => [ "headers", "@version"]
    uppercase => [ "VO" ]
    convert => { "production" => "boolean" }
    copy => { "@timestamp" => "ingest_timestamp" }
    copy => { "[result][reorders]" => "reorders" }
    copy => { "[result][received]" => "received" }
    copy => { "[result][loss]" => "loss" }
    copy => { "[result][lost]" => "lost" }
    copy => { "[result][sent]" => "sent" }
    copy => { "[result][duplicates]" => "duplicates" }
  }

  if [result][roundtrips]{
    # mutate{
    #   copy => { "[result][mean][/\d+(\.\d+)?/]" => "mean" }
    #   copy => { "[result][max][/\d+(\.\d+)?/]" => "max" }
    #   copy => { "[result][min][/\d+(\.\d+)?/]" => "min" }
    #   copy => { "[result][stddev][/\d+(\.\d+)?/]" => "stddev" }
    # }
    ruby {
        code => '
            mean_str = event.get("[result][mean]");
            if mean_str
                match = mean_str[/\d+(\.\d+)?/]
                event.set("mean", match.to_f) if match
            end

            min_str = event.get("[result][min]");
            if min_str
                match = min_str[/\d+(\.\d+)?/]
                event.set("min", match.to_f) if match
            end

            max_str = event.get("[result][max]");
            if max_str
                match = max_str[/\d+(\.\d+)?/]
                event.set("max", match.to_f) if match
            end

            stddev_str = event.get("[result][stddev]");
            if stddev_str
                match = stddev_str[/\d+(\.\d+)?/]
                event.set("stddev", match.to_f) if match
            end

            rtripsArray = event.get("[result][roundtrips]");
            if rtripsArray && rtripsArray.length > 0 && rtripsArray[0]
                event.set("packet_size", rtripsArray[0]["length"]);
            end
        '
    }
  }

  uuid {
    target    => "[@metadata][id]"
  }

  if ![tags] { # for problematic things don't remove fields
    mutate{
      remove_field => ["type", "test", "result", "@timestamp"] 
      convert => { "ipv6" => "boolean" }
    }
  }

}

output {
  pipeline { send_to => ["es-output"] }
}
