input { pipeline { address => "ps-status" } }

filter {

  mutate {
    add_field => { "[@metadata][type]" => "ps_status_write" } 
    remove_field => [ "headers", "@version", "host"]
    copy => { "@timestamp" => "ingest_timestamp" }
  }
  
  # memcached {
  #   hosts => ["memcached"]
  #   get => {
  #     "vo_%{[ps_host]}" => "[VO]"
  #     "sitename_%{[ps_host]}" => "[site]"
  #     "rcsite_%{[ps_host]}" => "[rcsite]"
  #     "production_%{[ps_host]}" => "[production]"
  #   }
  # }
  
  mutate { 
    rename => { "ps_host" => "[host]" } 
    uppercase => [ "VO" ]
    convert => { "production" => "boolean" }
  }

  uuid {
    target    => "[@metadata][id]"
  }

  if ![tags] { # for problematic things don't remove fields
    mutate{
      remove_field => ["type", "@timestamp"] 
    }
  }

}

output {
  pipeline { send_to => ["es-output"] }
}
